-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- TB_DOMAIN_DETAIL TABLE CREATE SQL
CREATE TABLE TB_DOMAIN_DETAIL
(
    `DOMAIN_NAME`      VARCHAR(50)     NOT NULL     COMMENT '도메인명',
    `DOMAIN_DESC`      VARCHAR(255)    NULL         COMMENT '도메인설명',
    `DOMAIN_REASONER`  VARCHAR(5)      NOT NULL     COMMENT '도메인REASONER',
    `CREATION_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`      DATETIME        NULL         COMMENT '수정일시',
    `USER_ID`          VARCHAR(50)     NULL         COMMENT '사용자ID',
    PRIMARY KEY (DOMAIN_NAME)
);

ALTER TABLE TB_DOMAIN_DETAIL COMMENT '도메인상세';


-- TB_CASE_STRUCTURE TABLE CREATE SQL
CREATE TABLE TB_CASE_STRUCTURE
(
    `DOMAIN_NAME`     VARCHAR(50)     NOT NULL     COMMENT '도메인명',
    `ATTRIBUTE_ID`    INT             NOT NULL     COMMENT '사례항목ID',
    `VALUE_TYPE_ID`   INT             NOT NULL     COMMENT '값유형ID',
    `ATTRIBUTE_NAME`  VARCHAR(255)    NULL         COMMENT '사례항목명',
    `CREATION_DATE`   DATETIME        DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`     DATETIME        NULL         COMMENT '수정일시',
    `USER_ID`         VARCHAR(50)     NULL         COMMENT '사용자ID',
    PRIMARY KEY (DOMAIN_NAME, ATTRIBUTE_ID)
);

ALTER TABLE TB_CASE_STRUCTURE COMMENT '사례구조';

ALTER TABLE TB_CASE_STRUCTURE ADD CONSTRAINT FK_CASESTRUCTURE_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_RULE_CONCLUSION TABLE CREATE SQL
CREATE TABLE TB_RULE_CONCLUSION
(
    `DOMAIN_NAME`      VARCHAR(50)     NOT NULL     COMMENT '도메인명',
    `CONCLUSION_ID`    INT             NOT NULL     COMMENT '결론ID',
    `VALUE_TYPE_ID`    INT             NOT NULL     COMMENT '값유형ID',
    `CONCLUSION_NAME`  VARCHAR(255)    NOT NULL     COMMENT '결론명',
    `CREATION_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`      DATETIME        NULL         COMMENT '수정일시',
    `USER_ID`          VARCHAR(50)     NULL         COMMENT '사용자ID',
    PRIMARY KEY (DOMAIN_NAME, CONCLUSION_ID)
);

ALTER TABLE TB_RULE_CONCLUSION COMMENT 'RULE결론';

ALTER TABLE TB_RULE_CONCLUSION ADD CONSTRAINT FK_RULECONCLUSION_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_RULE_STRUCTURE TABLE CREATE SQL
CREATE TABLE TB_RULE_STRUCTURE
(
    `DOMAIN_NAME`     VARCHAR(50)    NOT NULL     COMMENT '도메인명',
    `RULE_ID`         INT            NOT NULL     COMMENT 'RULEID',
    `PARENT_RULE_ID`  INT            NOT NULL     COMMENT '부모RULEID',
    `CONCLUSION_ID`   INT            NOT NULL     COMMENT '결론ID',
    `CREATION_DATE`   DATETIME       DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`     DATETIME       NULL         COMMENT '수정일시',
    `USER_ID`         VARCHAR(50)    NULL         COMMENT '사용자ID',
    PRIMARY KEY (DOMAIN_NAME, RULE_ID)
);

ALTER TABLE TB_RULE_STRUCTURE COMMENT 'RULE구조';

ALTER TABLE TB_RULE_STRUCTURE ADD CONSTRAINT FK_RULESTRUCTURE_RULECONCLUSION_CONCLUSIONID FOREIGN KEY (CONCLUSION_ID)
 REFERENCES TB_RULE_CONCLUSION (CONCLUSION_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_RULE_STRUCTURE ADD CONSTRAINT FK_RULESTRUCTURE_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_RULE_CORNERSTONES TABLE CREATE SQL
CREATE TABLE TB_RULE_CORNERSTONES
(
    `DOMAIN_NAME`    VARCHAR(50)    NOT NULL     COMMENT '도메인명',
    `RULE_ID`        INT            NOT NULL     COMMENT 'RULEID',
    `CASE_ID`        INT            NOT NULL     COMMENT '사례ID',
    `CREATION_DATE`  DATETIME       DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`    DATETIME       NULL         COMMENT '수정일시',
    `USER_ID`        VARCHAR(50)    NULL         COMMENT '사용자ID',
    PRIMARY KEY (DOMAIN_NAME, RULE_ID, CASE_ID)
);

ALTER TABLE TB_RULE_CORNERSTONES COMMENT 'RULE코너스톤사례';

ALTER TABLE TB_RULE_CORNERSTONES ADD CONSTRAINT FK_RULECORNERSTONES_RULESTRUCTURE_RULEID FOREIGN KEY (RULE_ID)
 REFERENCES TB_RULE_STRUCTURE (RULE_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_RULE_CORNERSTONES ADD CONSTRAINT FK_RULECORNERSTONES_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_CATEGORICAL_VALUE TABLE CREATE SQL
CREATE TABLE TB_CATEGORICAL_VALUE
(
    `CATEGORICAL_VALUE_ID`  INT             NOT NULL    AUTO_INCREMENT COMMENT '카테고리VALUEID',
    `DOMAIN_NAME`           VARCHAR(50)     NOT NULL     COMMENT '도메인명',
    `ATTRIBUTE_ID`          INT             NOT NULL     COMMENT '사례항목ID',
    `VALUE_NAME`            VARCHAR(255)    NOT NULL     COMMENT '카테고리VALUE',
    `CREATION_DATE`         DATETIME        DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`           DATETIME        NULL         COMMENT '수정일시',
    `USER_ID`               VARCHAR(50)     NULL         COMMENT '사용자ID',
    PRIMARY KEY (CATEGORICAL_VALUE_ID)
);

ALTER TABLE TB_CATEGORICAL_VALUE COMMENT '카테고리VALUE';

ALTER TABLE TB_CATEGORICAL_VALUE ADD CONSTRAINT FK_CATEGORICALVALUE_CASESTRUCTURE_ATTRIBUTEID FOREIGN KEY (ATTRIBUTE_ID)
 REFERENCES TB_CASE_STRUCTURE (ATTRIBUTE_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_CATEGORICAL_VALUE ADD CONSTRAINT FK_CATEGORICALVALUE_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_CORNERSTONE_CASE TABLE CREATE SQL
CREATE TABLE TB_CORNERSTONE_CASE
(
    `DOMAIN_NAME`    VARCHAR(50)    NOT NULL     COMMENT '도메인명',
    `CASE_ID`        INT            NOT NULL     COMMENT '사례ID',
    `ATTRIBUTE_ID`   INT            NOT NULL     COMMENT '사례항목ID',
    `CASE_VALUE`     TEXT           NOT NULL     COMMENT '사례VALUE',
    `CREATION_DATE`  DATETIME       DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`    DATETIME       NULL         COMMENT '수정일시',
    `USER_ID`        VARCHAR(50)    NULL         COMMENT '사용자ID',
    PRIMARY KEY (DOMAIN_NAME, CASE_ID, ATTRIBUTE_ID)
);

ALTER TABLE TB_CORNERSTONE_CASE COMMENT '코너스톤사례';

ALTER TABLE TB_CORNERSTONE_CASE ADD CONSTRAINT FK_CORNERSTONECASE_CASESTRUCTURE_ATTRIBUTEID FOREIGN KEY (ATTRIBUTE_ID)
 REFERENCES TB_CASE_STRUCTURE (ATTRIBUTE_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_CORNERSTONE_CASE ADD CONSTRAINT FK_CORNERSTONECASE_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_CORNERSTONE_CASE ADD CONSTRAINT FK_CORNERSTONECASE_RULECORNERSTONES_CASEID FOREIGN KEY (CASE_ID)
 REFERENCES TB_RULE_CORNERSTONES (CASE_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_RULE_CONDITIONS TABLE CREATE SQL
CREATE TABLE TB_RULE_CONDITIONS
(
    `CONDITION_ID`     INT             NOT NULL    AUTO_INCREMENT COMMENT '조건ID',
    `DOMAIN_NAME`      VARCHAR(50)     NOT NULL     COMMENT '도메인명',
    `RULE_ID`          INT             NOT NULL     COMMENT 'RULEID',
    `ATTRIBUTE_ID`     INT             NOT NULL     COMMENT '사례항목ID',
    `OPERATOR_ID`      INT             NOT NULL     COMMENT '연산자ID',
    `CONDITION_VALUE`  VARCHAR(255)    NULL         COMMENT '조건VALUE',
    `CREATION_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `UPDATE_DATE`      DATETIME        NULL         COMMENT '수정일시',
    `USER_ID`          VARCHAR(50)     NULL         COMMENT '사용자ID',
    PRIMARY KEY (CONDITION_ID)
);

ALTER TABLE TB_RULE_CONDITIONS COMMENT 'RULE조건';

ALTER TABLE TB_RULE_CONDITIONS ADD CONSTRAINT FK_RULECONDITIONS_RULESTRUCTURE_RULEID FOREIGN KEY (RULE_ID)
 REFERENCES TB_RULE_STRUCTURE (RULE_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_RULE_CONDITIONS ADD CONSTRAINT FK_RULECONDITIONS_CASESTRUCTURE_ATTRIBUTEID FOREIGN KEY (ATTRIBUTE_ID)
 REFERENCES TB_CASE_STRUCTURE (ATTRIBUTE_ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_RULE_CONDITIONS ADD CONSTRAINT FK_RULECONDITIONS_DOMAINDETAIL_DOMAINNAME FOREIGN KEY (DOMAIN_NAME)
 REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_RULE_CORNERSTONE_INFERENCE_RESULT TABLE CREATE SQL
CREATE TABLE TB_RULE_CORNERSTONE_INFERENCE_RESULT
(
    `INSTANCE_ID`    INT            NOT NULL    AUTO_INCREMENT COMMENT '인스턴스ID',
    `DOMAIN_NAME`    VARCHAR(50)    NOT NULL     COMMENT '도메인명',
    `CASE_ID`        INT            NOT NULL     COMMENT '사례ID',
    `RULE_ID`        INT            NOT NULL     COMMENT 'RULEID',
    `CREATION_DATE`  DATETIME       DEFAULT CURRENT_TIMESTAMP  COMMENT '생성일시',
    `USER_ID`        VARCHAR(50)    NULL         COMMENT '사용자ID',
    PRIMARY KEY (INSTANCE_ID)
);

ALTER TABLE TB_RULE_CORNERSTONE_INFERENCE_RESULT COMMENT 'RULE코너스톤추론결과';


