SELECT LMB_CODE
      ,RECEIPT_DATE
      ,RECEIPT_NO
      ,TEST_CODE
      ,TEST_SUB_CODE
      ,SPECIMEN_CODE
      ,TEST_NAME
      ,SPECIMEN_NAME
      ,WORK_NAME
      ,DEPARTMENT_CODE
      ,DEPARTMENT_NAME
      ,TEST_STAFF
      ,NUM_AREA
      ,NUM_CONC
      ,NUM_FROM_EQPT
      ,NUM_MATH_CONC
      ,CHR_RESULT
      ,MSPIKE_CNT
      ,RESULT_STATUS
      ,DECISION_CODE
      ,TEST_DATE
      ,EQUIPMENT_FLAG
      ,EQUIPMENT_CODE
      ,CREATION_DATE
      ,UPDATE_DATE
      ,USER_ID
 FROM TB_EP_TEST_RESULT
WHERE LMB_CODE = ?
  AND RECEIPT_DATE = ?
  AND RECEIPT_NO = ?
  AND TEST_CODE = ?
ORDER BY TEST_SUB_CODE
