SELECT LMB_CODE
      ,RECEIPT_DATE
      ,RECEIPT_NO
      ,HOSPITAL_CODE
      ,HOSPITAL_NAME
      ,PATIENT_NAME
      ,SEX
      ,AGE_YEAR
      ,AGE_DAY
      ,STATUS
      ,BRANCH_CODE
      ,BRANCH_NAME
      ,TOTAL_VOLUME
      ,PID_PRE
      ,PID_AFTER
      ,HOSPITAL_CHART_NO
      ,CREATION_DATE
      ,UPDATE_DATE
      ,USER_ID
 FROM TB_EP_RECEIPT
WHERE LMB_CODE = ?
  AND RECEIPT_DATE = ?
  AND RECEIPT_NO = ?
