INSERT INTO TB_CASE_STRUCTURE
(DOMAIN_NAME,
 ATTRIBUTE_ID,
 VALUE_TYPE_ID,
 ATTRIBUTE_NAME,
 ATTRIBUTE_DESC,
 CREATION_DATE,
 UPDATE_DATE,
 USER_ID)
 VALUES
 (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL, ?)
