INSERT INTO TB_RULE_CONDITIONS
(DOMAIN_NAME,
 RULE_ID,
 ATTRIBUTE_ID,
 OPERATOR_ID,
 CONDITION_VALUE,
 CREATION_DATE,
 UPDATE_DATE,
 USER_ID
)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL, ?)