select LMB_CODE
      ,RECEIPT_DATE
      ,RECEIPT_NO
      ,TEST_CODE
      ,TEST_SUB_CODE
      ,SPECIMEN_CODE
      ,TEST_NAME
      ,SPECIMEN_NAME
      ,WORK_NAME
      ,DEPARTMENT_CODE
      ,DEPARTMENT_NAME
      ,TEST_STAFF
      ,EQUIPMENT_NUMERIC_RESULT
      ,NUMERIC_DEFAULT_RESULT
      ,NUMERIC_FINAL_RESULT
      ,CHAR_DEFAULT_RESULT
      ,CHAR_FINAL_RESULT
      ,RESULT_STATUS_FLAG
      ,DECISION_NUMRIC1
      ,DECISION_CHAR1
      ,DECISION_NUMRIC2
      ,DECISION_CHAR2
      ,TEST_DATE
      ,WORK_NO
      ,COMMENT_FLAG
      ,EQUIPMENT_FLAG
      ,WORK_STATUS
      ,FIRST_SAVE_USER_INFO
      ,FIRST_EDIT_FLAG
      ,SECOND_CONFIRM_USER_INFO
      ,SECOND_EDIT_FLAG
      ,EQUIPMENT_CODE
      ,CREATION_DATE
      ,UPDATE_DATE
      ,USER_ID
 from TB_PBS_TEST_RESULT
WHERE LMB_CODE = ?
  AND RECEIPT_DATE = ?
  AND RECEIPT_NO = ?
  AND TEST_CODE like ?
ORDER BY TEST_SUB_CODE
