SELECT CATEGORICAL_VALUE_ID,
       DOMAIN_NAME,
       ATTRIBUTE_ID,
       VALUE_NAME,
       CREATION_DATE,
       UPDATE_DATE,
       USER_ID
FROM TB_CATEGORICAL_VALUE
WHERE DOMAIN_NAME = ?
  AND ATTRIBUTE_ID = ?