SELECT DOMAIN_NAME,
       ATTRIBUTE_ID,
       VALUE_TYPE_ID,
       ATTRIBUTE_NAME,
       ATTRIBUTE_DESC,
       CREATION_DATE,
       UPDATE_DATE,
       USER_ID
FROM TB_CASE_STRUCTURE
WHERE DOMAIN_NAME = ?
