SELECT CONDITION_ID,
       DOMAIN_NAME,
       RULE_ID,
       ATTRIBUTE_ID,
       OPERATOR_ID,
       CONDITION_VALUE,
       CREATION_DATE,
       UPDATE_DATE,
       USER_ID
FROM TB_RULE_CONDITIONS
WHERE DOMAIN_NAME = ?
