-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- TB_DOMAIN_DETAIL TABLE CREATE SQL
CREATE TABLE TB_DOMAIN_DETAIL
(
    "DOMAIN_NAME"      VARCHAR(50)     NOT NULL,
    "DOMAIN_DESC"      VARCHAR(255)    NULL,
    "DOMAIN_REASONER"  VARCHAR(5)      NOT NULL,
    "CREATION_DATE"    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"      DATETIME        NULL,
    "USER_ID"          VARCHAR(50)     NULL,
    CONSTRAINT PK_TB_DOMAIN_DETAIL PRIMARY KEY (DOMAIN_NAME)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인상세',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인설명',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL', 'COLUMN', 'DOMAIN_DESC'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인REASONER',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL', 'COLUMN', 'DOMAIN_REASONER'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_DOMAIN_DETAIL', 'COLUMN', 'USER_ID'
GO


-- TB_CASE_STRUCTURE TABLE CREATE SQL
CREATE TABLE TB_CASE_STRUCTURE
(
    "DOMAIN_NAME"     VARCHAR(50)     NOT NULL,
    "ATTRIBUTE_ID"    INT             NOT NULL,
    "VALUE_TYPE_ID"   INT             NOT NULL,
    "ATTRIBUTE_NAME"  VARCHAR(255)    NULL,
    "CREATION_DATE"   DATETIME        DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"     DATETIME        NULL,
    "USER_ID"         VARCHAR(50)     NULL,
    CONSTRAINT PK_TB_CASE_STRUCTURE PRIMARY KEY (DOMAIN_NAME, ATTRIBUTE_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례구조',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례항목ID',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'ATTRIBUTE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '값유형ID',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'VALUE_TYPE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례항목명',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'ATTRIBUTE_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_CASE_STRUCTURE', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_CASE_STRUCTURE
    ADD CONSTRAINT FK_TB_CASE_STRUCTURE_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO


-- TB_RULE_CONCLUSION TABLE CREATE SQL
CREATE TABLE TB_RULE_CONCLUSION
(
    "DOMAIN_NAME"      VARCHAR(50)     NOT NULL,
    "CONCLUSION_ID"    INT             NOT NULL,
    "VALUE_TYPE_ID"    INT             NOT NULL,
    "CONCLUSION_NAME"  VARCHAR(255)    NOT NULL,
    "CREATION_DATE"    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"      DATETIME        NULL,
    "USER_ID"          VARCHAR(50)     NULL,
    CONSTRAINT PK_TB_RULE_CONCLUSION PRIMARY KEY (DOMAIN_NAME, CONCLUSION_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULE결론',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '결론ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'CONCLUSION_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '값유형ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'VALUE_TYPE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '결론명',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'CONCLUSION_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONCLUSION', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_RULE_CONCLUSION
    ADD CONSTRAINT FK_TB_RULE_CONCLUSION_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO


-- TB_RULE_STRUCTURE TABLE CREATE SQL
CREATE TABLE TB_RULE_STRUCTURE
(
    "DOMAIN_NAME"     VARCHAR(50)    NOT NULL,
    "RULE_ID"         INT            NOT NULL,
    "PARENT_RULE_ID"  INT            NOT NULL,
    "CONCLUSION_ID"   INT            NOT NULL,
    "CREATION_DATE"   DATETIME       DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"     DATETIME       NULL,
    "USER_ID"         VARCHAR(50)    NULL,
    CONSTRAINT PK_TB_RULE_STRUCTURE PRIMARY KEY (DOMAIN_NAME, RULE_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULE구조',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULEID',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'RULE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '부모RULEID',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'PARENT_RULE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '결론ID',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'CONCLUSION_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_RULE_STRUCTURE', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_RULE_STRUCTURE
    ADD CONSTRAINT FK_TB_RULE_STRUCTURE_CONCLUSION_ID_TB_RULE_CONCLUSION_CONCLUSION_ID FOREIGN KEY (CONCLUSION_ID)
        REFERENCES TB_RULE_CONCLUSION (CONCLUSION_ID)
GO

ALTER TABLE TB_RULE_STRUCTURE
    ADD CONSTRAINT FK_TB_RULE_STRUCTURE_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO


-- TB_RULE_CORNERSTONES TABLE CREATE SQL
CREATE TABLE TB_RULE_CORNERSTONES
(
    "DOMAIN_NAME"    VARCHAR(50)    NOT NULL,
    "RULE_ID"        INT            NOT NULL,
    "CASE_ID"        INT            NOT NULL,
    "CREATION_DATE"  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"    DATETIME       NULL,
    "USER_ID"        VARCHAR(50)    NULL,
    CONSTRAINT PK_TB_RULE_CORNERSTONES PRIMARY KEY (DOMAIN_NAME, RULE_ID, CASE_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULE코너스톤사례',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULEID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES', 'COLUMN', 'RULE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES', 'COLUMN', 'CASE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONES', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_RULE_CORNERSTONES
    ADD CONSTRAINT FK_TB_RULE_CORNERSTONES_RULE_ID_TB_RULE_STRUCTURE_RULE_ID FOREIGN KEY (RULE_ID)
        REFERENCES TB_RULE_STRUCTURE (RULE_ID)
GO

ALTER TABLE TB_RULE_CORNERSTONES
    ADD CONSTRAINT FK_TB_RULE_CORNERSTONES_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO


-- TB_CATEGORICAL_VALUE TABLE CREATE SQL
CREATE TABLE TB_CATEGORICAL_VALUE
(
    "CATEGORICAL_VALUE_ID"  INT             IDENTITY,
    "DOMAIN_NAME"           VARCHAR(50)     NOT NULL,
    "ATTRIBUTE_ID"          INT             NOT NULL,
    "VALUE_NAME"            VARCHAR(255)    NOT NULL,
    "CREATION_DATE"         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"           DATETIME        NULL,
    "USER_ID"               VARCHAR(50)     NULL,
    CONSTRAINT PK_TB_CATEGORICAL_VALUE PRIMARY KEY (CATEGORICAL_VALUE_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '카테고리VALUE',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '카테고리VALUEID',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'CATEGORICAL_VALUE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례항목ID',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'ATTRIBUTE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '카테고리VALUE',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'VALUE_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_CATEGORICAL_VALUE', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_CATEGORICAL_VALUE
    ADD CONSTRAINT FK_TB_CATEGORICAL_VALUE_ATTRIBUTE_ID_TB_CASE_STRUCTURE_ATTRIBUTE_ID FOREIGN KEY (ATTRIBUTE_ID)
        REFERENCES TB_CASE_STRUCTURE (ATTRIBUTE_ID)
GO

ALTER TABLE TB_CATEGORICAL_VALUE
    ADD CONSTRAINT FK_TB_CATEGORICAL_VALUE_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO


-- TB_CORNERSTONE_CASE TABLE CREATE SQL
CREATE TABLE TB_CORNERSTONE_CASE
(
    "DOMAIN_NAME"    VARCHAR(50)    NOT NULL,
    "CASE_ID"        INT            NOT NULL,
    "ATTRIBUTE_ID"   INT            NOT NULL,
    "CASE_VALUE"     TEXT           NOT NULL,
    "CREATION_DATE"  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"    DATETIME       NULL,
    "USER_ID"        VARCHAR(50)    NULL,
    CONSTRAINT PK_TB_CORNERSTONE_CASE PRIMARY KEY (DOMAIN_NAME, CASE_ID, ATTRIBUTE_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '코너스톤사례',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례ID',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'CASE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례항목ID',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'ATTRIBUTE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례VALUE',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'CASE_VALUE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_CORNERSTONE_CASE', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_CORNERSTONE_CASE
    ADD CONSTRAINT FK_TB_CORNERSTONE_CASE_ATTRIBUTE_ID_TB_CASE_STRUCTURE_ATTRIBUTE_ID FOREIGN KEY (ATTRIBUTE_ID)
        REFERENCES TB_CASE_STRUCTURE (ATTRIBUTE_ID)
GO

ALTER TABLE TB_CORNERSTONE_CASE
    ADD CONSTRAINT FK_TB_CORNERSTONE_CASE_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO

ALTER TABLE TB_CORNERSTONE_CASE
    ADD CONSTRAINT FK_TB_CORNERSTONE_CASE_CASE_ID_TB_RULE_CORNERSTONES_CASE_ID FOREIGN KEY (CASE_ID)
        REFERENCES TB_RULE_CORNERSTONES (CASE_ID)
GO


-- TB_RULE_CONDITIONS TABLE CREATE SQL
CREATE TABLE TB_RULE_CONDITIONS
(
    "CONDITION_ID"     INT             IDENTITY,
    "DOMAIN_NAME"      VARCHAR(50)     NOT NULL,
    "RULE_ID"          INT             NOT NULL,
    "ATTRIBUTE_ID"     INT             NOT NULL,
    "OPERATOR_ID"      INT             NOT NULL,
    "CONDITION_VALUE"  VARCHAR(255)    NULL,
    "CREATION_DATE"    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_DATE"      DATETIME        NULL,
    "USER_ID"          VARCHAR(50)     NULL,
    CONSTRAINT PK_TB_RULE_CONDITIONS PRIMARY KEY (CONDITION_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULE조건',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '조건ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'CONDITION_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULEID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'RULE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례항목ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'ATTRIBUTE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '연산자ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'OPERATOR_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '조건VALUE',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'CONDITION_VALUE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '수정일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'UPDATE_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CONDITIONS', 'COLUMN', 'USER_ID'
GO

ALTER TABLE TB_RULE_CONDITIONS
    ADD CONSTRAINT FK_TB_RULE_CONDITIONS_RULE_ID_TB_RULE_STRUCTURE_RULE_ID FOREIGN KEY (RULE_ID)
        REFERENCES TB_RULE_STRUCTURE (RULE_ID)
GO

ALTER TABLE TB_RULE_CONDITIONS
    ADD CONSTRAINT FK_TB_RULE_CONDITIONS_ATTRIBUTE_ID_TB_CASE_STRUCTURE_ATTRIBUTE_ID FOREIGN KEY (ATTRIBUTE_ID)
        REFERENCES TB_CASE_STRUCTURE (ATTRIBUTE_ID)
GO

ALTER TABLE TB_RULE_CONDITIONS
    ADD CONSTRAINT FK_TB_RULE_CONDITIONS_DOMAIN_NAME_TB_DOMAIN_DETAIL_DOMAIN_NAME FOREIGN KEY (DOMAIN_NAME)
        REFERENCES TB_DOMAIN_DETAIL (DOMAIN_NAME)
GO


-- TB_RULE_CORNERSTONE_INFERENCE_RESULT TABLE CREATE SQL
CREATE TABLE TB_RULE_CORNERSTONE_INFERENCE_RESULT
(
    "INSTANCE_ID"    INT            IDENTITY,
    "DOMAIN_NAME"    VARCHAR(50)    NOT NULL,
    "CASE_ID"        INT            NOT NULL,
    "RULE_ID"        INT            NOT NULL,
    "CREATION_DATE"  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    "USER_ID"        VARCHAR(50)    NULL,
    CONSTRAINT PK_TB_RULE_CORNERSTONE_INFERENCE_RESULT PRIMARY KEY (INSTANCE_ID)
)
GO

EXECUTE SYS.SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULE코너스톤추론결과',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '인스턴스ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT', 'COLUMN', 'INSTANCE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '도메인명',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT', 'COLUMN', 'DOMAIN_NAME'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사례ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT', 'COLUMN', 'CASE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    'RULEID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT', 'COLUMN', 'RULE_ID'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '생성일시',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT', 'COLUMN', 'CREATION_DATE'
GO

EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION',
    '사용자ID',
   'USER', DBO, 'TABLE', 'TB_RULE_CORNERSTONE_INFERENCE_RESULT', 'COLUMN', 'USER_ID'
GO


