-- TB_DOMAIN_DETAIL Table Create SQL
CREATE TABLE TB_DOMAIN_DETAIL
(
    `DOMAIN_NAME`      VARCHAR(50)     NOT NULL,
    `DOMAIN_DESC`      VARCHAR(255)    NULL,
    `DOMAIN_REASONER`  VARCHAR(5)      NOT NULL,
    `CREATION_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`      DATETIME        NULL,
    `USER_ID`          VARCHAR(50)     NULL,
    PRIMARY KEY (DOMAIN_NAME)
);

-- TB_CASE_STRUCTURE Table Create SQL
CREATE TABLE TB_CASE_STRUCTURE
(
    `DOMAIN_NAME`     VARCHAR(50)     NOT NULL,
    `ATTRIBUTE_ID`    INTEGER         NOT NULL,
    `VALUE_TYPE_ID`   INTEGER         NOT NULL,
    `ATTRIBUTE_NAME`  VARCHAR(255)    NOT NULL,
    `ATTRIBUTE_DESC`  VARCHAR(512)    NULL,
    `CREATION_DATE`   DATETIME        DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`     DATETIME        NULL,
    `USER_ID`         VARCHAR(50)     NULL,
    PRIMARY KEY (DOMAIN_NAME, ATTRIBUTE_ID)
);

-- TB_RULE_CONCLUSION Table Create SQL
CREATE TABLE TB_RULE_CONCLUSION
(
    `DOMAIN_NAME`      VARCHAR(50)     NOT NULL,
    `CONCLUSION_ID`    INTEGER             NOT NULL,
    `VALUE_TYPE_ID`    INTEGER             NOT NULL,
    `CONCLUSION_NAME`  VARCHAR(255)    NOT NULL,
    `CREATION_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`      DATETIME        NULL ,
    `USER_ID`          VARCHAR(50)     NULL ,
    PRIMARY KEY (DOMAIN_NAME, CONCLUSION_ID)
);

-- TB_RULE_STRUCTURE Table Create SQL
CREATE TABLE TB_RULE_STRUCTURE
(
    `DOMAIN_NAME`     VARCHAR(50)    NOT NULL,
    `RULE_ID`         INTEGER            NOT NULL,
    `PARENT_RULE_ID`  INTEGER            NOT NULL,
    `CONCLUSION_ID`   INTEGER            NOT NULL,
    `CREATION_DATE`   DATETIME       DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`     DATETIME       NULL,
    `USER_ID`         VARCHAR(50)    NULL,
    PRIMARY KEY (DOMAIN_NAME, RULE_ID)
);

-- TB_RULE_CORNERSTONES Table Create SQL
CREATE TABLE TB_RULE_CORNERSTONES
(
    `DOMAIN_NAME`    VARCHAR(50)    NOT NULL,
    `RULE_ID`        INTEGER            NOT NULL,
    `CASE_ID`        INTEGER            NOT NULL,
    `CREATION_DATE`  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`    DATETIME       NULL,
    `USER_ID`        VARCHAR(50)    NULL,
    PRIMARY KEY (DOMAIN_NAME, RULE_ID, CASE_ID)
);

-- TB_CATEGORICAL_VALUE Table Create SQL
CREATE TABLE TB_CATEGORICAL_VALUE
(
    `CATEGORICAL_VALUE_ID`  INTEGER             PRIMARY KEY AUTOINCREMENT,
    `DOMAIN_NAME`           VARCHAR(50)     NOT NULL,
    `ATTRIBUTE_ID`          INTEGER             NOT NULL,
    `VALUE_NAME`            VARCHAR(255)    NOT NULL,
    `CREATION_DATE`         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`           DATETIME        NULL,
    `USER_ID`               VARCHAR(50)     NULL
);

-- TB_CORNERSTONE_CASE Table Create SQL
CREATE TABLE TB_CORNERSTONE_CASE
(
    `DOMAIN_NAME`    VARCHAR(50)    NOT NULL,
    `CASE_ID`        INTEGER            NOT NULL,
    `ATTRIBUTE_ID`   INTEGER            NOT NULL,
    `CASE_VALUE`     TEXT           NOT NULL,
    `CREATION_DATE`  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`    DATETIME       NULL,
    `USER_ID`        VARCHAR(50)    NULL,
    PRIMARY KEY (DOMAIN_NAME, CASE_ID, ATTRIBUTE_ID)
);

-- TB_RULE_CONDITIONS Table Create SQL
CREATE TABLE TB_RULE_CONDITIONS
(
    `CONDITION_ID`     INTEGER             PRIMARY KEY AUTOINCREMENT,
    `DOMAIN_NAME`      VARCHAR(50)     NOT NULL,
    `RULE_ID`          INTEGER             NOT NULL,
    `ATTRIBUTE_ID`     INTEGER             NOT NULL,
    `OPERATOR_ID`      INTEGER             NOT NULL,
    `CONDITION_VALUE`  VARCHAR(255)    NULL ,
    `CREATION_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`      DATETIME        NULL,
    `USER_ID`          VARCHAR(50)     NULL
);

-- TB_RULE_CORNERSTONE_INFERENCE_RESULT Table Create SQL
CREATE TABLE TB_RULE_CORNERSTONE_INFERENCE_RESULT
(
    `INSTANCE_ID`    INTEGER            PRIMARY KEY AUTOINCREMENT,
    `DOMAIN_NAME`    VARCHAR(50)    NOT NULL,
    `CASE_ID`        INTEGER            NOT NULL,
    `RULE_ID`        INTEGER            NOT NULL,
    `CREATION_DATE`  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    `USER_ID`        VARCHAR(50)    NULL
);
